mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('word_count/', include('word_count.urls')),
    path('polls/', include('polls.urls')),
    

]

polls/urls.py
from django.urls import path

from . import views
app_name='polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
# ex: /polls/
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

word_count/urls.py
from django.urls import path

from . import views


app_name ='word_count'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:target_id>/details', views.details, name='details'),
    path('search/',views.search, name='search'),
    #path('<int:target_id>/details/analyze', views.analyze, name= 'analyze')
]

polls/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timezone.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

word_count/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
# Create your models here.

class Target(models.Model):
    #this is the URL primary key
    target_text = models.CharField(max_length=200)
    search_date= models.DateTimeField('date searched')
    body_text =models.CharField(max_length= 20000)
    def __str__(self):
        return self.target_text
class WordList(models.Model):
    target= models.ForeignKey(Target,on_delete=models.CASCADE, default=None)
    common_words= JSONField()
    def __str__(self):
        return str(self.common_words)

word_count/forms.py
from django import forms

class WebScrapeForm(forms.Form):
    search_url = forms.URLField( initial="http://", label="Insert URL")

polls/views.py
from django.shortcuts import render

# Create your views here.
from .models import Question
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from django.views import generic



#these views are using a generic template provided by the django framework
#this is a common control pattern in these applications so it is streamlining this process:
#   1) get data from database based on some parameter passed via the url
#   2) loading a template with the dat
#   3) return the template to the browser


#this generic view is meant to display a list of objects
class IndexView(generic.ListView):
    #template_name is used a variable used to tell django which template to use
    template_name = 'polls/index.html'
    #context_object_name will provide the view with the name of the list we are showing to the browser
    #auto generated name is possible, but ould be question_list, and we are only looking at 5 most
    #recent, so it is relevant to define this explicitly
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

#display a detailed page for a particular object
#expects the primary key value captured from the URL to be called "pk"
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'



#this view is still hardcoded since this modifies data, and has some backend logic which isnt
#represented in the built-in generic views
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

word_count/views.py
from django.shortcuts import render
from .models import Target, WordList
# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .forms import WebScrapeForm
from django.utils import timezone

def index(request):
    target_list = Target.objects.all()
    #the following line is redundant now because the render method automatically loads the template located
    #at in the templates directory structure of this app.

    context = {
        'target_list': target_list,
    }
    return render(request, "word_count/index.html", context)

def details(request, target_id):
    target = get_object_or_404(Target, pk=target_id)
    context = {"target_id" : target_id,
               "body_text": target.body_text,
               "target_text": target.target_text

               }
    return render(request, 'word_count/details.html', context)
def analyze(request, target_id):
    context= {}
    return render(request, reverse('word_count:analyze').strip('/')+ ".html", context)

def search(request):
    if request.method== "POST":
        #we need to validate the form, so take the info from the HTTPRequest and populate a new WebScrapeForm with ti
        context={}
        form = WebScrapeForm(request.POST)
        if form.is_valid():
           # try:

                scraped_data = web_scrape(form.cleaned_data["search_url"])
                if scraped_data:
                    this_target = Target.objects.create(search_date=timezone.now(), target_text=form.cleaned_data["search_url"], body_text =scraped_data[:20000] )
                    WordList.objects.create(target=this_target, common_words=find_most_common_words(scraped_data))

                    return HttpResponseRedirect(reverse("word_count:index"))
                else:

                    raise Exception
           # except:
                context["error_message"]= "exception after form was validated"
                context["form"]= form

                return render(request, reverse('word_count:search').strip('/')+".html", context)
       # else:
       ##     context["error_message"] = "URL or Web Error"
       #     context["form"] = form

       #     return render(request, reverse('word_count:search').strip('/')+".html", context)

    else:
        #then this is the user's first intereaction with the form view: need to populate the form without
        #any values, and allow user to enter a URL
        context = {
            'form' : WebScrapeForm()}

        return render(request, reverse('word_count:search').strip('/')+".html", context)


#NOTE: Normally this code should be kept in a location that ISNT the public django server, for security/exploit reasons
import urllib.request
import re
from bs4 import BeautifulSoup
from urllib.error import HTTPError
import nltk
from nltk.corpus import stopwords

import wordcloud

def web_scrape(url):
    try:
        response = urllib.request.urlopen(url)
    except HTTPError as e:
        print(e)
        raise Exception("HTTPError")
    soup = BeautifulSoup(response, 'html.parser')

    return soup.get_text()

def find_most_common_words(text):
    wordfreqs = wordcloud.WordCloud().process_text(text)
    print (sorted(wordfreqs.items(), key=lambda kv: kv[1],reverse=True))
    return (sorted(wordfreqs.items(), key=lambda kv: kv[1],reverse=True))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

word_count/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<HEAD>
<TITLE>Word_Count: {% block title %}Home{%  endblock %} {{ target_text }}</TITLE>
</HEAD>

<h1>Word_Count:{% block header %}Index{%  endblock %}</h1>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'word_count/style.css' %}">

<div id="content-div">
   <hr>
    {% block content %}
    {% endblock %}
    <a href="{% url 'word_count:index'%}">back</a>
</div>
<br>
<HR>
Sofia Besenski 2020 github@sofiabesenski4
</BODY>

</HTML>

word_count/templates/word_count/details.html
{% extends "base.html" %}

{%  block title %}Details: {{ target_text }}{%  endblock %}


{% block content %}

    <h1>Details</h1>
    <H2>URL= <a href="{{ target_text}}">{{ target_text}}</a>
        </H2>
    <b>Target ID</b> : {{ target_id }}<br>
    <h2><b>Body Text:</h2></b><br>
    {{ body_text}}
    <br><br>
    <hr>

{% endblock %}

word_count/templates/word_count/index.html
{% extends "base.html" %}

{% load static %}


{% block title %}Web Scraper and Text Analysis Tool{% endblock %}
{%  block header %}Index {% endblock %}
{% block content %}
    <H1><a href="{% url 'word_count:search' %}"><b>Search</b></a>
    </H1>

    <H2>Previous Searches</H2>
    {% if target_list %}
        <ul>
        {% for target in target_list %}
            <li><a href="{% url 'word_count:details' target.id %}">{{ target.target_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No targets are listed.</p>
    {% endif %}
{% endblock %}

word_count/templates/word_count/search.html
{% extends "base.html" %}
{% load static %}

{% block title %}Search{% endblock %}
{% block header %}Search{% endblock %}
{% block content %}
{% if error_message %}  {{ error_message  }} {% endif%}
<form  method="post">
{% csrf_token %}
    {{ form }}
  <button type="submit">Submit</button>
</form>


{% endblock %}